# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1144, 599)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setStyleSheet("#Form{\n"
"    background-color: rgb(5, 17, 77);\n"
"}")
        Form.setWindowFilePath("")
        self.birinci = QtWidgets.QComboBox(Form)
        self.birinci.setGeometry(QtCore.QRect(110, 330, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.birinci.setFont(font)
        self.birinci.setAccessibleDescription("")
        self.birinci.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.birinci.setStyleSheet("")
        self.birinci.setObjectName("birinci")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.birinci.addItem("")
        self.ikinci = QtWidgets.QComboBox(Form)
        self.ikinci.setGeometry(QtCore.QRect(110, 520, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.ikinci.setFont(font)
        self.ikinci.setAccessibleDescription("")
        self.ikinci.setStyleSheet("")
        self.ikinci.setObjectName("ikinci")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.ikinci.addItem("")
        self.eded = QtWidgets.QLineEdit(Form)
        self.eded.setGeometry(QtCore.QRect(100, 250, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(22)
        self.eded.setFont(font)
        self.eded.setStyleSheet("QLineEdit{\n"
"    border:3px solid;\n"
"    border-radius:20px\n"
"}")
        self.eded.setAlignment(QtCore.Qt.AlignCenter)
        self.eded.setObjectName("eded")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(220, 0, 621, 221))
        self.label.setStyleSheet("background-image: url(:/logo/logo.PNG);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logo/logo.PNG"))
        self.label.setScaledContents(True)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(260, 410, 121, 91))
        self.label_2.setStyleSheet("background-image: url(:/ox-2/ox-2.PNG);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/ox-2/ox-2.PNG"))
        self.label_2.setScaledContents(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(380, 410, 121, 91))
        self.label_3.setStyleSheet("background-image: url(:/ox-2/ox-2.PNG);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/ox-2/ox-2.PNG"))
        self.label_3.setScaledContents(False)
        self.label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_3.setObjectName("label_3")
        self.hesabla = QtWidgets.QPushButton(Form)
        self.hesabla.setGeometry(QtCore.QRect(710, 490, 261, 81))
        self.hesabla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hesabla.setStyleSheet("QPushButton {\n"
"    color: goldenrod;\n"
"    font-size: 20px;\n"
"    border: 0.3em solid goldenrod;\n"
"    border-radius: 0.5em;\n"
"    width: 12em;\n"
"    height: 3em;\n"
"    text-transform: uppercase;\n"
"    font-weight: bold;\n"
"    font-family: sans-serif;\n"
"    letter-spacing: 0.1em;\n"
"    text-align: center;\n"
"    line-height: 3em;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: white;\n"
"    border: 0.3em solid goldenrod;\n"

"}"
"QPushButton:pressed {\n"
"    color: goldenrod;\n"
"    border: 0.3em solid goldenrod;\n"

"}"
)
        self.hesabla.setObjectName("hesabla")
        self.main_label = QtWidgets.QLabel(Form)
        self.main_label.setGeometry(QtCore.QRect(640, 290, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro")
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.main_label.setFont(font)
        self.main_label.setStyleSheet("color: rgb(255, 255, 127);")
        self.main_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_label.setObjectName("main_label")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(650, 280, 371, 80))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.birinci.setItemText(0, _translate("Form", "2"))
        self.birinci.setItemText(1, _translate("Form", "3"))
        self.birinci.setItemText(2, _translate("Form", "4"))
        self.birinci.setItemText(3, _translate("Form", "5"))
        self.birinci.setItemText(4, _translate("Form", "6"))
        self.birinci.setItemText(5, _translate("Form", "7"))
        self.birinci.setItemText(6, _translate("Form", "8"))
        self.birinci.setItemText(7, _translate("Form", "9"))
        self.birinci.setItemText(8, _translate("Form", "10"))
        self.birinci.setItemText(9, _translate("Form", "11"))
        self.birinci.setItemText(10, _translate("Form", "12"))
        self.birinci.setItemText(11, _translate("Form", "13"))
        self.birinci.setItemText(12, _translate("Form", "14"))
        self.birinci.setItemText(13, _translate("Form", "15"))
        self.birinci.setItemText(14, _translate("Form", "16"))
        self.ikinci.setItemText(0, _translate("Form", "2"))
        self.ikinci.setItemText(1, _translate("Form", "3"))
        self.ikinci.setItemText(2, _translate("Form", "4"))
        self.ikinci.setItemText(3, _translate("Form", "5"))
        self.ikinci.setItemText(4, _translate("Form", "6"))
        self.ikinci.setItemText(5, _translate("Form", "7"))
        self.ikinci.setItemText(6, _translate("Form", "8"))
        self.ikinci.setItemText(7, _translate("Form", "9"))
        self.ikinci.setItemText(8, _translate("Form", "10"))
        self.ikinci.setItemText(9, _translate("Form", "11"))
        self.ikinci.setItemText(10, _translate("Form", "12"))
        self.ikinci.setItemText(11, _translate("Form", "13"))
        self.ikinci.setItemText(12, _translate("Form", "14"))
        self.ikinci.setItemText(13, _translate("Form", "15"))
        self.ikinci.setItemText(14, _translate("Form", "16"))
        self.eded.setPlaceholderText(_translate("Form", "Enter the number.. "))
        self.hesabla.setText(_translate("Form", "CALCULATE"))
        self.main_label.setText(_translate("Form", "None"))
import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
